### ISSUE TITLE
Define Network API

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1442]
All public APIs should be well-defined and covered by unit tests. This includes the C++ `nupic.core` Network API.

---
- [ ] [Current nupic.core Network API 100% covered by unit tests](https://github.com/numenta/nupic.core/issues/211)
- [ ] [Current nupic.core Network API is fully documented with docstrings](https://github.com/numenta/nupic.core/issues/212)
- [ ] [Create pure C++ example code for Network API](https://github.com/numenta/nupic.core/issues/142)
- [ ] [Create command line example for Network API](https://github.com/numenta/nupic.core/issues/175)
- [ ] [Create complete C++ demo for Network API for a real problem](https://github.com/numenta/nupic.core/issues/176)
- [x] [Create a Python network example with hierarchy](https://github.com/numenta/nupic/issues/570)
