### ISSUE TITLE
Define OPF API

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1488]
OPF API needs to be fully defined by tests, documentation, and a wiki overview. 

---
- [ ] [OPF API is 100% covered by unit tests](https://github.com/numenta/nupic/issues/1443)
- [ ] [OPF API is fully documented with docstrings](https://github.com/numenta/nupic/issues/1444)
- [ ] [OPF API overview is documented on the wiki](https://github.com/numenta/nupic/issues/1487)
