### ISSUE TITLE
Upgrade to numpy 1.9.2

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1516]
This message has been a [pain](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2014-July/004344.html) since we open-sourced NuPIC:

    RuntimeError: module compiled against API version 9 but this version of numpy is 7

New users run into this, and need to uninstall their system version of `numpy` to fix it. It needs to be fixed once and for all on our end, and I think upgrading is the best way to fix it. 

* * *

- [ ] [Coordinate encoder should use integer seeds for random number generation](https://github.com/numenta/nupic/issues/1517)
- [x] [Upgrade to numpy 1.9.2 (linux64)](https://github.com/numenta/nupic-linux64/issues/32)
- [x] [Upgrade to numpy 1.9.2 (darwin64)](https://github.com/numenta/nupic-darwin64/issues/15)

**Comment by flavius** [comment]
@rhyolight  Any news about this? I am using archlinux and I'd like to use nupic within sagemath, however installing nupic makes sagemath kaputt because sagemath was linked against the latest version of numpy.

**Comment by rhyolight** [comment]
https://github.com/numenta/nupic/blob/e60704bb0f20f08594dd37c83ebb2e5a6b0cb1ca/requirements.txt#L21

We are already there!

**Comment by flavius** [comment]
@rhyolight Well then sage is compiled with numpy 1.11, because I get ```RuntimeError: module compiled against API version 0xa but this version
of numpy is 0x9```

In general, I don't think it's a good idea for the nupic.bindings to mess with my system's packages when installing:

```
localhost# pip2 install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.5-cp27-none-linux_x86_64.whl
Collecting nupic.bindings==0.4.5 from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.5-cp27-none-linux_x86_64.whl
  Downloading https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.5-cp27-none-linux_x86_64.whl (4.1MB)
    100% |████████████████████████████████| 4.1MB 231kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytest-cov==1.6 in /usr/lib/python2.7/site-packages (from nupic.bindings==0.4.5)
Collecting numpy==1.9.2 (from nupic.bindings==0.4.5)
  Using cached numpy-1.9.2-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): pytest-xdist==1.8 in /usr/lib/python2.7/site-packages (from nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): pytest==2.5.1 in /usr/lib/python2.7/site-packages (from nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.6 in /usr/lib/python2.7/site-packages (from pytest-cov==1.6->nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): execnet>=1.0.8 in /usr/lib/python2.7/site-packages (from pytest-xdist==1.8->nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.19 in /usr/lib/python2.7/site-packages (from pytest==2.5.1->nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.6 in /usr/lib/python2.7/site-packages (from cov-core>=1.6->pytest-cov==1.6->nupic.bindings==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): apipkg>=1.4 in /usr/lib/python2.7/site-packages (from execnet>=1.0.8->pytest-xdist==1.8->nupic.bindings==0.4.5)
Installing collected packages: numpy, nupic.bindings
  Found existing installation: numpy 1.11.2
    Uninstalling numpy-1.11.2:
      Successfully uninstalled numpy-1.11.2
  Found existing installation: nupic.bindings 0.4.10.dev0
    Uninstalling nupic.bindings-0.4.10.dev0:
      Successfully uninstalled nupic.bindings-0.4.10.dev0
Successfully installed numpy-1.9.2 nupic.bindings-0.4.5
```

**Comment by rhyolight** [comment]
Python packaging and installation confuses me, so I might be wrong here, but don't you have control over where python packages are installed? You can use the `--user` or `--prefix` options in setuptools or pip to install locally. You can also always use `virtualenv`. @oxtopus might have more to add.

**Comment by flavius** [comment]
The point is using htm while inside sagemath.

**Comment by rhyolight** [comment]
I think there is a core issue here I'm failing to recognize. @flavius can you help me define it? It obviously has something to do with sagemath and numpy. What change would you make to nupic to make it work properly, assuming that nupic (and any other python module) might explicitly depend upon a specific numpy version?

I think it is reasonable for a python module to explicitly depend upon any other library (for whatever reasons they wish). Am I wrong? Thanks for your help!

**Comment by flavius** [comment]
@rhyolight my problem is that the command:

```pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.5-cp27-none-linux_x86_64.whl```

installs a version of numpy thus replacing the existing numpy, and in doing so, it is screwing sagemath.

Ideally, there should be two ways to make it play well together: either embed the required numpy, vendored and pinned to the version required, into nupic.core whl (whatever that is, it's new to me), or, if numpy already exists on the system, use that one, instead of overwriting it.

**Comment by oxtopus** [comment]
re:

> 2. if numpy already exists on the system, use that one, instead of overwriting it.

The behavior you describe is specific to `pip`, independent of `nupic` or `nupic.bindings`.  I'm not familiar with Sage, but you should be able to install `pip install nupic --no-deps` and then manage the dependencies on your own.  It's a bit unconventional, but here's what you could do:

```
pip install \
  asteval==0.9.1 \
  coverage==3.7.1 \
  mock==1.0.1 \
  ordereddict==1.1 \
  psutil==1.0.1 \
  pytest==2.5.1 \
  pytest-cov==1.6 \
  pytest-xdist==1.8 \
  python-dateutil==2.1 \
  PyYAML==3.10 \
  unittest2==0.5.1 \
  validictory==0.9.1 \
  PyMySQL==0.6.2 \
  DBUtils==1.1 \
  pyproj==1.9.3 \
  prettytable==0.7.2
pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.4.5-cp27-none-linux_x86_64.whl nupic==0.5.5 --no-deps
```

I'm not 100% certain it will work for your purposes, but I tested it in virtualenv on my mac with no problems.

**Comment by flavius** [comment]
Of course it will work in virtualenv, but how could it work in "two virtualenvs" at the same time?

How could one use nupic in sagemath?

**Comment by rhyolight** [comment]
@flavius @oxtopus Let's continue on https://github.com/numenta/nupic/issues/3397.
