### ISSUE TITLE
Move from cmake to setuptools for building and preparation for distribution

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1617]
In order to properly distribute NuPIC as a pip package, we need to transfer from a cmake build to a complete setuptools build. This incorporates several related subtasks that are involved in this cleanup, listed below.

* * *

- [x] [Put all functionally of "CMakeLists.txt" into "setup.py"](https://github.com/numenta/nupic/issues/1573)
- [X] [Refactor bindings to adhere to setuptools standards](https://github.com/numenta/nupic/issues/1616)
- [x] [Use python test commands in README and travis (remove cmake commands)](https://github.com/numenta/nupic/issues/1618)

**Comment by david-ragazzi** [comment]
@rhyolight Now this can be closed due to https://github.com/numenta/nupic/pull/1658 be merged.

**Comment by rhyolight** [comment]
:confetti_ball:
