### ISSUE TITLE
Compiler performance optimizations

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1682]
Optimizations can be made to speed up compilation and runtime performance. 

* * *

- [x] [determine Travis deployment build vs local build and set CC flags accordingly](https://github.com/numenta/nupic.core/issues/287) (nupic.core)
- [x] [Explore effects of aggressive compiler optimizations on speed](https://github.com/numenta/nupic.core/issues/192) (nupic.core)
- [x] [Compiler flags optimizations](https://github.com/numenta/nupic/issues/1679) (nupic)
- [x] [Speed up TemporalPooler](https://github.com/numenta/nupic.core/issues/280) (nupic.core)
- [x] [Resolution on unsigned >= 0 checks](https://github.com/numenta/nupic/issues/370) (nupic)
- [x] [Swig optimizations](https://github.com/numenta/nupic/pull/1663) (nupic)
- [ ] [speed up python part of TemporalPooler when using c++ TP binding](https://github.com/numenta/nupic/issues/1672)

**Comment by rhyolight** [comment]
Closing because #1672 is the only remaining issue, and I moved it into #1708 to keep it simple.
