### ISSUE TITLE
Windows binary build and deployment

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1786]
Just like we build and deploy NuPIC binaries for OS X and Linux, we should do the same for Windows. 

* * *

- [x] [Windows Python support](https://github.com/numenta/nupic.core/issues/553) (`nupic.core`)
- [x] [Appveyor build creates nupic.bindings binary files and uploads them to S3 for iterative builds](https://github.com/numenta/nupic.core/issues/570) (`nupic.core`)
- [x] [Appveyor build configured to download nupic.bindings from S3](https://github.com/numenta/nupic/issues/2488)
- [x] [Create a release process to deploy nupic.bindings to pypi for Windows](https://github.com/numenta/nupic.core/issues/571) (`nupic.core`)
- [x] [Update Appveyor CI job to create binaries on release tags](https://github.com/numenta/nupic/issues/1889)
- [X] [NuPIC Readme and Wiki needs to describe Windows PyPi installation](https://github.com/numenta/nupic/issues/2878)

**Comment by rcrowder** [comment]
For reference;
https://packaging.python.org/en/latest/appveyor.html

**Comment by rhyolight** [comment]
Next up:  [Create NuPIC Appveyor configuration for Windows builds](https://github.com/numenta/nupic/issues/1888)

**Comment by rcrowder** [comment]
Need to tidy this up, now that the Core has https://github.com/numenta/nupic.core/issues/553

**Comment by rhyolight** [comment]
Indeed. I'll take a pass at it today.

**Comment by rhyolight** [comment]
@rcrowder How does this newly organized super issue work?

**Comment by rcrowder** [comment]
@rhyolight One remaining task here. Issues have been raised to address the remaining work.

**Comment by rcrowder** [comment]
@rhyolight The 64-bit version for Windows, that matches closely the build process for 64-bit Linux, has been out in the wild for a while now. Scott and Vitaly's work on removing pre-built and packaged external dependencies in nupic.core (Apr, Yaml, etc.), have gone a long way to having 32-bit OS support on Windows and Linux variants. This issue is mainly relates to the build and install for 64-bit Windows. I'll close this one off now.
