### ISSUE TITLE
OS X Build & Installation Problems

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1809]
This ticket groups together all current OS X build and binary installation bug reports. 

* * * 

- [x] [README should warn users of binary incompatibility with OS X non system python](https://github.com/numenta/nupic/issues/1820)
- [x] [OS X binaries don't work with Homebrew Python [OS X 10]](https://github.com/numenta/nupic/issues/1813)
- [x] [Unable to find library '.../nupic/libcpp_region.so’ \[OS X 10.10 Binary Installation\]](https://github.com/numenta/nupic/issues/1804)
- [x] [Unable to locate hot gym data file \[OS X 10.10 Binary Installation\]](https://github.com/numenta/nupic/issues/1805)
- [x] [cannot import nupic.bindings.math \[OS X 10.10 Homebrew Python\]](https://github.com/numenta/nupic/issues/1791)
- [x] [Error running unit tests: ImportError: No module named math [OS X 10.10 Binary Installation]](https://github.com/numenta/nupic/issues/1806)
