### ISSUE TITLE
Linux Build and Installation Problems

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1810]
Lists issues related to problems building or installing from binary on all Linux.

* * *

- [x] [gcc: internal compiler error: Killed (program cc1plus) [Ubuntu12.04]](https://github.com/numenta/nupic/issues/1803)
- [x] [LTO build problem with GCC 4.9 [Ubuntu 12.04]](https://github.com/numenta/nupic/issues/1698)
- [x] [LTO version mismatch during build on [Ubuntu]](https://github.com/numenta/nupic/issues/1740)
- [x] [Binary pip install error [Debian / Anaconda Python]: Cap'n Proto local compilation errors](https://github.com/numenta/nupic/issues/1774)
