### ISSUE TITLE
Monitor Mixin Framework improvements

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1854]
Work dealing with Monitor Mixin Framework.

* * *

- [ ] [Monitor Mixin Framework: Refactor duplicate instances of prettyPrintTitle in Metric, Plot and Trace](https://github.com/numenta/nupic/issues/1467)
- [ ] [Use Monitor Mixin Framework in hello_sp as example](https://github.com/numenta/nupic/issues/1466)
- [ ] [Rename sourceCell to presynapticCell in Temporal Memory Monitor Mixin](https://github.com/numenta/nupic/issues/1590)
- [ ] [Add unpredicted => active cells to Temporal Memory Monitor Mixin](https://github.com/numenta/nupic/issues/1594)
- [ ] [Extend Temporal Memory Monitor Mixin to show cell activity](https://github.com/numenta/nupic/issues/1825)
