### ISSUE TITLE
Anomaly detection improvements

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1879]
Organized workflow for anomaly related issues/enhancements.

- [ ] Swarming optimization of Anomaly
  - [X] [Expose anomaly params to OPF for swarming](https://github.com/numenta/nupic/issues/1305)
  - [ ] [New Anomaly metric to drive optimization during swarming](https://github.com/numenta/nupic/issues/1841)
    - [ ] [Pass extra information to Metric (CLAModel, Anomaly, ..)](https://github.com/numenta/nupic/issues/1842)
    - [ ] [`minimize=` optimization criterion/Metric can be set as Metric instance/ID, not only constructed from string](https://github.com/numenta/nupic/issues/1848)
  - [ ] [Tool for anomaly supervised learning/parameter optimization](https://github.com/numenta/nupic/issues/1830)
- [ ] [New anomaly mode: binary discretization](https://github.com/numenta/nupic/issues/1840)
- [ ] [New anomaly computation - taking unexpected observations into account](https://github.com/numenta/nupic/issues/1300)
- [ ] Problems
  - [ ] [Handle missing anomaly spikes](https://github.com/numenta/nupic/issues/948)
  - [ ] [Boosting creates artificial anomaly spikes](https://github.com/numenta/nupic/issues/823)

**Comment by cogmission** [comment]
May I ask if swarming has been refactored out of the OPF? Is it now a stand-alone function?

**Comment by breznak** [comment]
it's not. There's an issue for that, but without much progress yet I think..

**Comment by rhyolight** [comment]
It's a big job.

**Comment by rhyolight** [comment]
One thing we might be missing here is incorporating the anomaly likelihood into the model itself (like the anomaly score).

If a user creates a model and passes data into it, there is a period of time where the anomaly likelihood is always `0.5` until it gathers enough data to start it's windowed calculation. If this model is serialized and restarted, this same learning period applies again. Ideally, this resurrected model would retain the anomaly likelihood data so it could continue where it left off instead of starting with a bunch of `0.5` values upon resurrection.

**Comment by breznak** [comment]
@rhyolight good point. We might open an issue for that, it would fall to the `anomaly_likelihood`'s responsibility to handle that during de/serialization. Actually, I'm not sure if it's not already handeled? As the prev values are stored in a `[]` and that would be serialized fine. Same goes for `MovingAverage` class.

**Comment by rhyolight** [comment]
It is not currently handled, as I noticed it occurred recently for @anubhavchaturvedi.

**Comment by breznak** [comment]
https://github.com/numenta/nupic/issues/1908
