### ISSUE TITLE
Pluggable Components

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2093]
This means allowing people using NuPIC as a library to write their own encoders, regions, etc without having to modify the NuPIC codebase itself. This is crucial for making NuPIC extensible for users.

* * *

- [x] [Create network example with pluggable encoders](https://github.com/numenta/nupic/issues/2161)
- [x] [Allow clients to register custom Python regions](https://github.com/numenta/nupic/issues/2057)
- [x] [Allow clients to register custom C++ regions](https://github.com/numenta/nupic.core/issues/359)

**Comment by breznak** [comment]
Just an idea for workaround for recent issues, which is "modular" - should be use `-DSERIALIZATION` and wrap all the CAPNP code & tests in `#ifdef` ? So people who don't care for serialization of models could avoid the issues? (works as a workaround too)
CC @scottpurdy

**Comment by scottpurdy** [comment]
@breznak - I would like to avoid preprocessor conditional blocks for features if at all possible.
