### ISSUE TITLE
FileRecordStream with multiple categories

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/nupic#2335]
Currently FileRecordStream only accepts one category label per data instance; [spec is here](https://github.com/numenta/nupic/blob/master/nupic/data/file_record_stream.py#L132). We would like the functionality for multiple category labels per row; i.e. multiple columns labeled with `C`.

**Comment by BoltzmannBrain** [comment]
Because we'd like to allow variable number of categories across records in a data file -- i.e. some records can have 1 category, others may have 4, etc. -- we'll stick to a single categories column. This issue then is to allow multiple categories to be specified by a list, requiring the following:
- [ ] record stream support for "list" field type: #2364
- [ ] extending the "category" special flag to support both "int" and "list" field types and making corresponding network changes: #2365
- [ ] updating the knn classifier to support multiple input categories: #2366

**Comment by BoltzmannBrain** [comment]
Resolved w/ PRs #2367, #2368, and #2370.
