### ISSUE TITLE
Hypersearch Decoupling Milestone 1: Separate swarming code into core Hypersearch files and NuPIC-specific Client

### ISSUE THREAD

**Issue by mihail911** [numenta/nupic#2391]
The Hypersearch API should be defined in such a way that a wide variety of clients can make use of the library in domain-specific ways (e.g. a NuPIC specific client, etc. ) The NuPIC-client will continue to reside within NuPIC, making API calls as appropriate from the hypersearch framework. Hypersearch should not depend at all on anything outside of hypersearch ( besides the standard library). The NuPIC-client can depend on Hypersearch as well as NuPIC. 

Sub-issues associated with this milestone:
- [x] [Error Codes] (https://github.com/numenta/nupic/issues/2390)
- [x] [Utils] (https://github.com/numenta/nupic/issues/2392)
- [x] [DictUtils] (https://github.com/numenta/nupic/issues/2403)
- [x] [ExperimentUtils] (https://github.com/numenta/nupic/issues/2416)
- [x] [Sorted JSON Dump Migration] (https://github.com/numenta/nupic/issues/2421)
- [x] [JSON Helpers] (https://github.com/numenta/nupic/issues/2424)
- [x] [Resolved ExtendedLogger Dependency] (https://github.com/numenta/nupic/issues/2426)

**Comment by rhyolight** [comment]
@mihail911 Updated issue description with [proper subtask formatting](https://github.com/numenta/nupic/wiki/Roadmap#proper-sub-task-formatting).
