### ISSUE TITLE
Clean up NuPIC builds and test indiscrepancies

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#2503]
Even though Travis-CI builds against `master` seem to be passing, we have several problems.

* * *

- [ ] [RandomProto capnp import failure in hotgym_regression_test.py ](https://github.com/numenta/nupic/issues/2467)
- [ ] [Test H10 in TM integration test is invalid](https://github.com/numenta/nupic/issues/2478)
- [ ] [NuPIC build cannot find py_region_test](https://github.com/numenta/nupic/issues/2502)
- [ ] [test fails on Ubuntu 12.04 & 14.04.3](https://github.com/numenta/nupic/issues/2484)

**Comment by rhyolight** [comment]
@scottpurdy @jcasner This super ticket represents all the issues I think are important to get our NuPIC builds back on track. Let me know if you think I've missed any?
