### ISSUE TITLE
Fix Duplicate ID issues

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2556]
This is a super issue to track the various pycapnp Duplicate ID exceptions.

Here are the known causes:

- Executing code while in the root of the repo can cause imports of the local source files rather than the installed files.

Next step is is re-enable pycapnp and address any instances of the duplicate id exception. Hopefully we can identify a cause behind each of the cases reported below.

Here are various reports:

* * *

- [ ] [Duplicate ID capnp exception from ScalarEncoder](https://github.com/numenta/nupic/issues/2113)
- [x] [test fails on Ubuntu 12.04 & 14.04.3](https://github.com/numenta/nupic/issues/2484)
- [x] [RandomProto capnp import failure in hotgym_regression_test.py](https://github.com/numenta/nupic/issues/2467)
- [ ] [Failing Swarming Tests](https://github.com/numenta/nupic/issues/2171)
- [x] [Some UnitTests get stuck on serialization - This seems related although it is a different issue.](https://github.com/numenta/nupic/issues/2148)

**Comment by chetan51** [comment]
@scottpurdy How do we re-enable pycapnp?

**Comment by scottpurdy** [comment]
@chetan just install it (0.5.5 was last version we used). The imports in nupic catch ImportError when attempting to `import capnp`

**Comment by chetan51** [comment]
You mean locally? I thought when you said "re-enable pycapnp" you meant in our continuous testing system.

**Comment by scottpurdy** [comment]
Well for CI like travis you'd put it in the requirements.txt for nupic. We need to look at the various duplicate id reports and see if we can reproduce any before merging pycapnp back in.

**Comment by chetan51** [comment]
Looks like we haven't received any more reports of this issue. Can we close?

**Comment by rhyolight** [comment]
@scottpurdy close this?

**Comment by scottpurdy** [comment]
Woohoo!
