### ISSUE TITLE
Switch default TemporalMemory implementation from python to C++

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic#2949]
This is a super issue to track progress.

- [ ] [Updating bindings for TemporalMemory to work with tests in nupic](https://github.com/numenta/nupic.core/issues/828)
- [ ] [Update AbstractTemporalMemoryTest to support C++ TemporalMemory](https://github.com/numenta/nupic/issues/2946)
- [ ] [Add C++ TemporalMemory to temporal_memory_performance_test.py](https://github.com/numenta/nupic/issues/2947)
- [ ] [Create compatibility test for python vs C++ TemporalMemory](https://github.com/numenta/nupic/issues/2948)

**Comment by scottpurdy** [comment]
Should we include some speed and accuracy comparison with TP10X2 as well?

**Comment by chetan51** [comment]
@scottpurdy Speed comparison would happen with https://github.com/numenta/nupic/issues/2947. As for accuracy, maybe we can do that with NAB?

**Comment by scottpurdy** [comment]
Yeah NAB would give pretty good confidence.

**Comment by SaganBolliger** [comment]
@chetan51 I think you've got the last two items in that list (adding accessors to py and c++) linked the wrong way around.

**Comment by chetan51** [comment]
@SaganBolliger Fixed, thanks.

**Comment by chetan51** [comment]
All remaining issues are in review.

**Comment by chetan51** [comment]
The main task remaining here is to finish investigating the discrepancy between C++ and python when `predictedSegmentDecrement ` is nonzero (or when `permanenceDecrement` is large). The `temporal_memory_compatibility_test.py` script is what tests that (change the appropriate parameters in `network_creation_common.py`).
