### ISSUE TITLE
Implement new SDR classifier

### ISSUE THREAD

**Issue by ywcui1990** [numenta/nupic#3058]
This is a super issue to track progress.

* * * 

- [ ] [Implement SDR Classifier in NuPIC] (https://github.com/numenta/nupic/issues/3053)
- [ ] [Update CLA classifier region to allow the use of SDR classifier] (https://github.com/numenta/nupic/issues/3054)
- [ ] [Implement SDR classifier in nupic.core] (https://github.com/numenta/nupic/issues/3055)
- [ ] [Test SDR classifier with OPF and hotgym] (https://github.com/numenta/nupic/issues/3056)
- [ ] [Update sample code with the SDR classifier] (https://github.com/numenta/nupic/issues/3057)
