### ISSUE TITLE
Establish a release process and versioning strategy for nupic

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#408]
NuPIC needs to start a release process, even if we begin with "alpha", "beta", etc. We need to get a process going to we can start to think about proper releasing. The first step is to prepare a release road map so everyone can see and discuss what issues should go in what release candidates.

First, we'll attempt to version the `nupic` repository, ignoring the details of `nupic.core`'s separate versioning. The `nupic.core` version numbers will be independent of `nupic`, and will come later. 

- Depends on ~~[nupic should build assuming nupic.core is a standard external library](https://github.com/numenta/nupic/issues/1483)~~

* * *

- [X] Create release [road map](http://status.numenta.org/roadmap) (@rhyolight)
- [x] [Introduce formal changelog file into codebase](https://github.com/numenta/nupic/issues/1448) (@rhyolight)
- [x] Document and enforce [semantic versioning](http://semver.org/).  (@rhyolight)
- [x] [NuPIC version number is defined in one place in the codebase](https://github.com/numenta/nupic/issues/1447) (@rhyolight)
- [x] [Create a release tag trigger for release processing](https://github.com/numenta/nupic/issues/1514) (@rhyolight)
- [x] [Configuration base class must use pkg_resources to find config file(s)](https://github.com/numenta/nupic/issues/1593) (@rhyolight)
- [x] [Update setuptools setup to create proper sdists](https://github.com/numenta/nupic/issues/1731) (@rhyolight)
- [x] [Upload complete nupic packages to pypi on every release](https://github.com/numenta/nupic/issues/1515) (@rhyolight)
- [x] [Publish binaries build with GCC instead of clang](https://github.com/numenta/nupic.core/issues/286) (@rhyolight)
- [x] [Ensure platform-specific wheel files are produced during release](https://github.com/numenta/nupic/issues/1729) (@rhyolight)
- [x] Document release branch strategy <https://github.com/numenta/nupic/wiki/Releases> (@rhyolight)
- [x] [gcc error on pip source distribution install: OS X](https://github.com/numenta/nupic/issues/1733) (@rhyolight)
- [x] [Linux pip installs from are downloading OS X binary package](https://github.com/numenta/nupic/issues/1734) (@rhyolight)
- [x] [package_data is missing for linux wheels](https://github.com/numenta/nupic/issues/1736) (@rhyolight)
- [x] [Linux wheels deploy to S3 on release](https://github.com/numenta/nupic/issues/1744) (@rhyolight)
- [x] [Update README with new binary installation instructions](https://github.com/numenta/nupic/issues/1747) (@rhyolight)
